filegroup(
    name = "realistic_transport_root_tests_inventory_resources",
    srcs = [
        "BUCK",
        "run_buck_pytest.sh",
    ] + glob([
        "*.bzl",
        "*.py",
        "*.pyc",
        "*.pyi",
        "*.pyo",
        "*.so",
        "**/*.bzl",
        "**/*.py",
        "**/*.pyc",
        "**/*.pyi",
        "**/*.pyo",
        "**/*.so",
    ]),
    visibility = ["PUBLIC"],
)

filegroup(
    name = "test_sources",
    srcs = glob(["test_*.py"]),
)

sh_test(
    name = "tests",
    args = [
        "$(exe //tools:pytest_runner)",
        "-q",
        "tests",
    ],
    deps = [
        "//:repository_resources",
        "//experiments/realistic_transport:lib",
        ":test_sources",
        "//tools:pytest_runner",
    ],
    labels = ["buck2_run_from_project_root"],
    test = "run_buck_pytest.sh",
)
