#!/usr/bin/env python3
"""The anonymous-package contract, pinned in code rather than in shipped data.

The submission supplement contains two files that are anonymized copies of the
study's evidence: one metadata string is replaced so that double-blind review is
not defeated by a version-control identifier.  `ANONYMIZATION.json` ships with
the supplement so a reviewer is told what changed.

`ANONYMIZATION.json` is a reviewer-visible, reviewer-editable file, so it is a
*claim*, never an authority.  An earlier version of the shipped verifiers
compared each packaged file against the digest recorded in that declaration.
That let anyone edit a packaged file, recompute its `.sha256` sidecar, update the
declaration's `packaged_sha256`, and pass every check -- which is exactly the
mutation an independent reviewer demonstrated with `candidate_count`.

This module is the fix.  It pins, in code:

* the exact set of packaged paths -- no more, no fewer;
* the exact field name and replacement token;
* the exact content SHA-256 and byte count of the original evidence;
* the exact content SHA-256 and byte count of the sanitized bytes;
* the exact sidecar text that must sit next to each sanitized file;
* the exact declaration schema and record set.

Everything the shipped verifiers accept is measured against these constants.
`ANONYMIZATION.json` is then *validated against them*: it must agree exactly, and
disagreement is a failure of the declaration, not a new expectation.

Nothing here is a Git revision or an author-linked identifier.  Every hex string
below is a SHA-256 content digest of a file, which is what a reviewer needs in
order to check bytes, and which says nothing about who produced them.  The
removed value itself is deliberately absent from this file and from every other
shipped byte; it is recorded only in the internal release metadata.

The constants are generated by, and cross-checked against, the packaging step:
`submissions/tmlr_2026/package.py` refuses to build if the bytes it produces do
not match them, and a test asserts the same in the other direction, so the
contract cannot silently drift away from what is actually shipped.

Two modes, and the difference matters:

* **Optional repository mode** (the default).  A tree with no declaration is not
  a package, so there is no anonymization contract to check.  This is right for
  running the checker directly against the original committed evidence, and it
  is why repository tooling does not have to carry an anonymization file.
* **Required package mode** (`--require-package`, or the environment variable
  `CCE_REQUIRE_ANONYMOUS_PACKAGE=1`).  The tree *must* be an anonymous package:
  a missing declaration is a failure, not a pass.  Without this the omission of
  `ANONYMIZATION.json` silently downgrades a supplement to repository semantics,
  and a supplement carrying the original, author-linked evidence verifies clean.
  The shipped supplement entry point always runs in this mode, first, and stops
  there if it fails.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from collections.abc import Sequence
from pathlib import Path

DECLARATION_NAME = "ANONYMIZATION.json"

#: Set to 1/true/yes to require package mode without passing a flag.  The shipped
#: supplement entry point exports this, so every checker it runs inherits package
#: semantics even if a later step is invoked without its own flag.
ENV_REQUIRE_PACKAGE = "CCE_REQUIRE_ANONYMOUS_PACKAGE"

#: The single metadata field that packaging is permitted to replace.
PACKAGED_FIELD = "git_revision"

#: The placeholder written in its place.  Deliberately not forty hex characters:
#: it must not be mistakable for a commit or for a substitute provenance id.
REPLACEMENT_TOKEN = "withheld-for-double-blind-review"

#: The exact, complete set of files packaging may sanitize.  A packaged tree that
#: sanitizes anything else, or fails to sanitize one of these, is rejected.
CONTRACT: dict[str, dict[str, object]] = {
    "results/derived/transport_instantiation/full_aggregate.json": {
        "original_sha256":
            "0ddebd4915dd2e264e24b7b25047d24f86c3cdf63930a1e6df77585e0b97de02",
        "original_bytes": 77035403,
        "packaged_sha256":
            "279e40f790c7e4a1045cbf24c3d61d5b2f10d870d77bdb7ab42b7d6896dcfdcb",
        "packaged_bytes": 77035395,
    },
    "results/derived/transport_instantiation/selection.json": {
        "original_sha256":
            "8c16bec7cc220109df3fd7173c3d06ae6c6e1b95e9db5bc5b8c3377b3564f6f4",
        "original_bytes": 1282446,
        "packaged_sha256":
            "6cb37fe4e03384df11b59898874fb38f4cba39b2ab555f0ca14857ed20883e49",
        "packaged_bytes": 1282438,
    },
}

#: The provenance records that ship beside the two evidence files.  They are
#: NOT anonymized -- they carry no revision -- so they ship byte for byte, and
#: they are pinned here because nothing else covered them: the sidecar sweep
#: walks paper/tables and paper/figures only, so zeroing a provenance record's
#: `artifact_sha256` left `verify.sh` green.  A provenance record that no longer
#: names the digest of the artifact it describes is worthless as provenance, so
#: both the bytes and the binding are pinned.
PROVENANCE_PINS: dict[str, dict[str, object]] = {
    "results/derived/transport_instantiation/full_aggregate.json.provenance.json": {
        "sha256":
            "7018ce64f319e625b78ba0f24db4f73ad26aeb26d9d7642acbefb3d5a38816c6",
        "bytes": 2988054,
        "describes":
            "results/derived/transport_instantiation/full_aggregate.json",
        "artifact_sha256":
            "0ddebd4915dd2e264e24b7b25047d24f86c3cdf63930a1e6df77585e0b97de02",
        "input_set_sha256":
            "4af9f51467981326c4f99ef171dc21e3fb27beb4d519b65d28d18f678e65ef66",
        "input_count": 13923,
        "schema_version": 1,
    },
    "results/derived/transport_instantiation/selection.json.provenance.json": {
        "sha256":
            "91b9eaa773e9b237b0ca9c4d2052e6ff831a2c033b7d57c27b4502c4d8534bb5",
        "bytes": 903697,
        "describes": "results/derived/transport_instantiation/selection.json",
        "artifact_sha256":
            "8c16bec7cc220109df3fd7173c3d06ae6c6e1b95e9db5bc5b8c3377b3564f6f4",
        "input_set_sha256":
            "fb202efb21389eb5a5f25d5ea5e28fa592dc237cf5d5410c76316fce8ca275a9",
        "input_count": 4321,
        "schema_version": 1,
    },
}

#: The exact compiled closure, pinned outside the manifest that declares it.
#:
#: `SOURCE_CLOSURE.json` says what pdfTeX opened.  Checking that file against
#: itself proves nothing, and a reviewer showed what that costs: deleting one
#: recorded figure CSV from the manifest left full supplement verification
#: green, because the file's `.sha256` sidecar still verified its bytes and
#: nothing required it to be *in the closure*.  A sidecar says "these bytes are
#: the ones I expect".  It cannot say "and the compiler read this file", which
#: is the claim the closure makes.
#:
#: So the expected set lives here instead, in the module that is already this
#: tree's authentication root.  It is exact in every direction: one entry per
#: compiled input, no more and no fewer, each bound to its repository path,
#: digest, byte count, role, and the archive that actually carries it.  Packaging
#: refuses to build if what it is about to record disagrees; the shipped checker
#: refuses to accept a package whose manifest disagrees.
#:
#: `ships_in` is the field that stopped `main.bbl` being described wrongly.  Its
#: bytes are in neither archive -- bibtex writes it during the build -- so the
#: only thing a reviewer can check it against is the digest pinned right here.
COMPILED_CLOSURE: dict[str, dict[str, object]] = {
    'appendix_cg.tex': {
        "repository": 'paper/appendix_cg.tex',
        "sha256": '2353183c8a0476dfae93617661546ef13c9592fb59d38fb200b8fdb37c8f13a4',
        "bytes": 4979,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_deferred.tex': {
        "repository": 'paper/appendix_deferred.tex',
        "sha256": 'daefcd86b173d6f0d6410d2e31360e6c614b77de81f8a268fedbb8ba38c3b706',
        "bytes": 115093,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_expfam.tex': {
        "repository": 'paper/appendix_expfam.tex',
        "sha256": '05344aef4698a8b746704298d148e5c34946e04f5cef5c5ca97e11bf7d2539be',
        "bytes": 1619,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_ggn.tex': {
        "repository": 'paper/appendix_ggn.tex',
        "sha256": 'a988dd441bdd97e0fdc45e1d30b529c53988394f1f92b6ff7fe103feb2c094ca',
        "bytes": 1361,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_onesided_proof.tex': {
        "repository": 'paper/appendix_onesided_proof.tex',
        "sha256": '409ab25ad527aa2245b7532a5d4797f0cfbc921b44a5e00f6fc36cf85dd80774',
        "bytes": 5951,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_protocol.tex': {
        "repository": 'paper/appendix_protocol.tex',
        "sha256": 'ff120f4422e4a98e7fc294671971051e75474371bc88afe160470656796cc5d7',
        "bytes": 28328,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_rates.tex': {
        "repository": 'paper/appendix_rates.tex',
        "sha256": '12f80de0727dd45e430c64f1985fc50d5a50fbeb50bc4b6cd5c2e101b8f0f390',
        "bytes": 9753,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'appendix_twosided.tex': {
        "repository": 'paper/appendix_twosided.tex',
        "sha256": '437a2d0c5527f5bb7a1c74157cace36ec84ea853cb141b89f8d9a199b68892d1',
        "bytes": 4819,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'availability.tex': {
        "repository": 'paper/availability.tex',
        "sha256": '47b7d95307c8454cf2319ceeb7e7f920c50517897df86d31c540e0a8d41d3fab',
        "bytes": 2757,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'body_conclusion.tex': {
        "repository": 'paper/body_conclusion.tex',
        "sha256": '141192bb23d1062098e41aa45508b8278a5d1786fe9d2aeff8e8cf083c74e3b6',
        "bytes": 4273,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'body_intro.tex': {
        "repository": 'paper/body_intro.tex',
        "sha256": 'dd79e288264996b0de62ab9653b772173fd6f6c857d01e790d56a1f6c6861333',
        "bytes": 6247,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'body_related.tex': {
        "repository": 'paper/body_related.tex',
        "sha256": 'c7d2f4bbd76fcf9f8ea20da79888d77d47d6801a68a9c1992d8374418b4ab6a2',
        "bytes": 8729,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'broader_impact.tex': {
        "repository": 'paper/broader_impact.tex',
        "sha256": '4651d8958460ca907aa81b8361d9af555d9aaf4d123f0e47c611a42478507468',
        "bytes": 669,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'cleveref.sty': {
        "repository": 'paper/texmf_vendor/cleveref.sty',
        "sha256": '58d7e2b67b8b165ec1c7e12dd2ea6edc807d5a61f68cb316267cea44fe128ef9',
        "bytes": 329481,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'fancyhdr.sty': {
        "repository": 'paper/tmlr_style/fancyhdr.sty',
        "sha256": '3d2922548e0e5f1a6c5676eda6ebb6dc20d7d305b4d8c2be5f1c833fb1084e6d',
        "bytes": 17086,
        "role": 'venue-template',
        "ships_in": 'source',
    },
    'figures/transport_instantiation_bound.tex': {
        "repository": 'paper/figures/transport_instantiation_bound.tex',
        "sha256": '9c6465521c216fa96fc6536044491684312108c510357f38cc92c0325319af3c',
        "bytes": 4242,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_bound_D-0p25.csv': {
        "repository": 'paper/figures/transport_instantiation_bound_D-0p25.csv',
        "sha256": '3959c9bcc08777c1c51ed7d9a1df24d5959dea87722651cc412e8cad1784e8dc',
        "bytes": 19634,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_bound_D-0p5.csv': {
        "repository": 'paper/figures/transport_instantiation_bound_D-0p5.csv',
        "sha256": 'f2f32585e282cb7a489a86b8d30b9f052c4c9966edcead37b3de3d194bb932bc',
        "bytes": 19506,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_bound_D-1.csv': {
        "repository": 'paper/figures/transport_instantiation_bound_D-1.csv',
        "sha256": '7a8d614df8164249f7bf6304230f3bfe948979beaebf331cb90f6bfb8c055a47',
        "bytes": 19301,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_bound_D-2.csv': {
        "repository": 'paper/figures/transport_instantiation_bound_D-2.csv',
        "sha256": 'f8f4e4d8fc055e71646f1df1a33cf7b6545b7b366f065ae0a7e3c1a6b4aae7f1',
        "bytes": 19293,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_regret.tex': {
        "repository": 'paper/figures/transport_instantiation_regret.tex',
        "sha256": '239ae5e923801ed1a2f9eafa75ba6a642e8bd2bb14ec2875c8d080f22ea5ec98',
        "bytes": 12544,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_regret_D-0p25.csv': {
        "repository": 'paper/figures/transport_instantiation_regret_D-0p25.csv',
        "sha256": '1b11f1ef4d29ff859dd887d7d65d25a58cf79d0df7bb01035a119f742d7525a4',
        "bytes": 62546,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_regret_D-0p5.csv': {
        "repository": 'paper/figures/transport_instantiation_regret_D-0p5.csv',
        "sha256": 'dbf0333c0ce3ef894b92b006465cf6729ccaae7f4c01f461c429406584f8b1bc',
        "bytes": 62117,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_regret_D-1.csv': {
        "repository": 'paper/figures/transport_instantiation_regret_D-1.csv',
        "sha256": '5b71b630e299e0eee0e326120eacb599fdf9403de6e4abace184b8b84d8c0aa5',
        "bytes": 61320,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_regret_D-2.csv': {
        "repository": 'paper/figures/transport_instantiation_regret_D-2.csv',
        "sha256": '993cf2ba45b2655c2e44948dfe63ea5ed0223ff500c3877d386e7436a06b7167',
        "bytes": 61328,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_tightness.tex': {
        "repository": 'paper/figures/transport_instantiation_tightness.tex',
        "sha256": '828590d0cab45e2621677474acec4ae1216857191d54e816d4f4b24a2fd276c2',
        "bytes": 4910,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_tightness_D-0p25.csv': {
        "repository": 'paper/figures/transport_instantiation_tightness_D-0p25.csv',
        "sha256": '83fcccb74aa1cc6828991cc304356252c4aa18e9263d54ef349fb2540547ed3d',
        "bytes": 13554,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_tightness_D-0p5.csv': {
        "repository": 'paper/figures/transport_instantiation_tightness_D-0p5.csv',
        "sha256": 'ee50921f06665269b9cffe059e0adbd735885b1f8869c638e6c1efedefa152b1',
        "bytes": 12170,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_tightness_D-1.csv': {
        "repository": 'paper/figures/transport_instantiation_tightness_D-1.csv',
        "sha256": 'cbc469c4b885f4a512b0ada7a3242ffd2e8e03c4896e466ba7f97ed0f5fc4f5d',
        "bytes": 12098,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'figures/transport_instantiation_tightness_D-2.csv': {
        "repository": 'paper/figures/transport_instantiation_tightness_D-2.csv',
        "sha256": 'c57502cf62d3a8deb53c4bb1d6a0e6eff1fb71ce604c124e1be204ff884e0db8',
        "bytes": 12471,
        "role": 'figure-data',
        "ships_in": 'supplement',
    },
    'legacy_dynamic.tex': {
        "repository": 'paper/legacy_dynamic.tex',
        "sha256": '4ff02a18f566647c8c83e6d37cf8790483edb469213f403defddbcc160fa165a',
        "bytes": 25914,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'macros.tex': {
        "repository": 'paper/macros.tex',
        "sha256": '0161bd1793fee89289ab990a267f89ba2e2d159ef997e649e032f6c304829f9d',
        "bytes": 2225,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'main.bbl': {
        "repository": None,
        "sha256": '9056fa74b6eddc581f2e0a9774c592bc2005fdf56e0e0b7aeb1a8ea3dfd2b57c',
        "bytes": 11998,
        "role": 'bibliography-output',
        "ships_in": 'neither',
    },
    'main.tex': {
        "repository": 'submissions/tmlr_2026/main.tex',
        "sha256": '783fcd34740bed03cea7d3de6316d5361db9174ae275e0d551e407a55a1043ca',
        "bytes": 6409,
        "role": 'entry-point',
        "ships_in": 'supplement',
    },
    'mathtools.sty': {
        "repository": 'paper/texmf_vendor/mathtools.sty',
        "sha256": '4c4bbd5e235f293dd773ad43b3aaebd3598a9d405b4ffe6326a9492157915085',
        "bytes": 56225,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'mhsetup.sty': {
        "repository": 'paper/texmf_vendor/mhsetup.sty',
        "sha256": 'c3ae1e23f43029fbfc271e3b1440a692e1cd924d1810430b99e4f2aa5b9ccf09',
        "bytes": 5582,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'microtype-pdftex.def': {
        "repository": 'paper/texmf_vendor/microtype-pdftex.def',
        "sha256": 'f196a58f713b3ec5e5a333645e031842859572c1b7e0d1a7d4e1dfc36896a5ea',
        "bytes": 49122,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'microtype.cfg': {
        "repository": 'paper/texmf_vendor/microtype.cfg',
        "sha256": '48d49af4c08491d0bb1c8a4ba189e41d2a5bff4811a3af56540f7e9a88673eaf',
        "bytes": 25351,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'microtype.sty': {
        "repository": 'paper/texmf_vendor/microtype.sty',
        "sha256": '26604a3f185a5f389061b035f6d534b971a25b18ae3d41864e77870402cff56c',
        "bytes": 72985,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'mt-cmr.cfg': {
        "repository": 'paper/texmf_vendor/mt-cmr.cfg',
        "sha256": 'ee8658bc3a8cec636afce4a7143811a4310f6c830b551dbed09a90836bb4cdf9',
        "bytes": 22870,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'mt-msa.cfg': {
        "repository": 'paper/texmf_vendor/mt-msa.cfg',
        "sha256": '3c55f887c103890580e078c409bed845562b27f3b98697f93d08856f103c31ca',
        "bytes": 5893,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'mt-msb.cfg': {
        "repository": 'paper/texmf_vendor/mt-msb.cfg',
        "sha256": 'f3ea01b4420c406dbf1b68dd9efe3b33ef2b5b28ba0031140e0b6082bbdda018',
        "bytes": 5558,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'notation.tex': {
        "repository": 'paper/notation.tex',
        "sha256": '4fd6d0cd33af7eee0754f58a913c0d31e82877a0602ac90aaa8570ee1133fb3e',
        "bytes": 3209,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'pgflibraryfillbetween.code.tex': {
        "repository": 'paper/texmf_vendor/pgflibraryfillbetween.code.tex',
        "sha256": '5f509db0338d04288db52164f3384e1dfa209e820b151d68568979385379baba',
        "bytes": 46361,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgflibrarypgfplots.surfshading.code.tex': {
        "repository": 'paper/texmf_vendor/pgflibrarypgfplots.surfshading.code.tex',
        "sha256": 'e90c556be8f468865ca2b656913ba8afc2220f2c163f02e0874731a6d34cdd64',
        "bytes": 22701,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgflibrarypgfplots.surfshading.pgfsys-pdftex.def': {
        "repository": 'paper/texmf_vendor/pgflibrarypgfplots.surfshading.pgfsys-pdftex.def',
        "sha256": 'c52c6c54e7ffd5e43094a13b33c6e93cbfa1f3fd6455cf2512102d19d3b7c49e',
        "bytes": 5907,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.code.tex',
        "sha256": 'b81c0ee2806033d4111b73f50400ff8865ae90accd3c6e7a6976e81c2a3aa52a',
        "bytes": 484290,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.errorbars.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.errorbars.code.tex',
        "sha256": '70c56e4ccf3448f53cfbb90046ada2683dbf2eec1cf586562fe78bcfe146b3de',
        "bytes": 22428,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.markers.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.markers.code.tex',
        "sha256": '59104418d1184b73a01e15b254ffb8c5d4320cf510673f095933d88e901617d6',
        "bytes": 12489,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.paths.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.paths.code.tex',
        "sha256": 'd11c8b83414c052bb39c678e49d81c5f0235de4af1bdf5dd75270e4de82f94a5',
        "bytes": 3533,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.revision.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.revision.tex',
        "sha256": '208f32e66b042889cf8597135ebcf7ee1cea04c5f8bf9ee7a2b7ed383436944c',
        "bytes": 516,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.scaling.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplots.scaling.code.tex',
        "sha256": '3e8298cf4d0f913a2ca6c2bba59d9894a42f8e9572671e4dd2f83f6bceb95b80',
        "bytes": 123680,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplots.sty': {
        "repository": 'paper/texmf_vendor/pgfplots.sty',
        "sha256": 'cb353b58769449f756c5c16f9d355c90c0714d1da1228bf912c3a5b208b4890b',
        "bytes": 4904,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsarray.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsarray.code.tex',
        "sha256": '38442c559fd7e7be2a812d4d809940795fc9535e6d571dbf52c5a0493b26f998',
        "bytes": 23537,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsbinary.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsbinary.code.tex',
        "sha256": '71271312b0668f69e03014f6c90fcf37112de363643661a2cbb77e047e86d75e',
        "bytes": 23050,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsbinary.data.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsbinary.data.code.tex',
        "sha256": 'd48a5679ca97f921aa11c6ac0aea9773f8791ab8cf71399ed731f44236d04eed',
        "bytes": 26859,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotscolor.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotscolor.code.tex',
        "sha256": '521c3db6439ff99c2dbcba5384f8006824ab4a4af28f86785ec9930968272536',
        "bytes": 23958,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotscolormap.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotscolormap.code.tex',
        "sha256": 'b0671f2833e4eb6ee2bd932bbd93f01f92e841b4f6941294b95d5b8075d720e9',
        "bytes": 88956,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotscoordprocessing.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotscoordprocessing.code.tex',
        "sha256": '765209b4b8739df96bd13c01b5573c043a4b2a3490c7c741d5fa9c7e0743973d',
        "bytes": 367035,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotscore.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotscore.code.tex',
        "sha256": '4c71ea64f5b3582f1d6346f9f9a782da20ed7a4c76e00ee1f73ee23186a1db9b',
        "bytes": 19944,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsdeque.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsdeque.code.tex',
        "sha256": '86843251927c29a021eac1635ee8650cfc06265281b50441d8cb6f67bb8504ee',
        "bytes": 4288,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotslibrary.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotslibrary.code.tex',
        "sha256": '12dfa15deed098538d51fb665a4f4ff759d8ef63d9216b38c19e87fbb0b476dc',
        "bytes": 3047,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsliststructure.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsliststructure.code.tex',
        "sha256": 'ef606fdf2ffc6197b9e1037860e1fe788cfa1aa3bf271a986dd6662b2e6526ca',
        "bytes": 13828,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsliststructureext.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsliststructureext.code.tex',
        "sha256": 'a4cd7e5531850e0e874c1096838ec55d62bf413dd7488f5316f730ce833f42db',
        "bytes": 24373,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsmatrix.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsmatrix.code.tex',
        "sha256": 'a22375071be85968f3b7489bd64c01f5317ca1ddadc0b7ab1f8257181d55a35b',
        "bytes": 18861,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsmeshplothandler.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsmeshplothandler.code.tex',
        "sha256": '285da39b32bee58c3cad318670a986b3097efd4442d2452d48abbf3727a47157',
        "bytes": 133871,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsmeshplotimage.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsmeshplotimage.code.tex',
        "sha256": '7da4d7c10e41e5fed5f54489deaf761a3d01e2353c47b345582666785805f18b',
        "bytes": 24402,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsoldpgfsupp_loader.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsoldpgfsupp_loader.code.tex',
        "sha256": 'a36a28ecd51df3dd0f63446f24a84290ec322095280578063ae9b94804014c37',
        "bytes": 12347,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsplothandlers.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsplothandlers.code.tex',
        "sha256": '5810ee1120735670e9d7c3edd9c0f1e2e9e77284a76804cb413ecd314fe9f1f2',
        "bytes": 117959,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsstackedplots.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsstackedplots.code.tex',
        "sha256": '77a129850572be38d1cb3540d5b6ac4a835f2335ba22a2f90cd4d05762b0bbf0',
        "bytes": 26190,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotssysgeneric.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotssysgeneric.code.tex',
        "sha256": '7124db702274395928a825f687081477f0de5ee9007b9a4a9208f28f209f67fe',
        "bytes": 3095,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotstableshared.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotstableshared.code.tex',
        "sha256": 'ae3fd038684fb1192d7a9059d5c8b261cccbf647f0f3d9ac084be882b5ec9895',
        "bytes": 83469,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsticks.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsticks.code.tex',
        "sha256": '7005297bdcb9afb98162d9d2f4e0555285bb025c8359413f9785f2a57ffd228a',
        "bytes": 91244,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsutil.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsutil.code.tex',
        "sha256": 'd385812ee2e3eebba3ae8356728e0e58697d9d508f4001ffad266de47f47886b',
        "bytes": 71110,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'pgfplotsutil.verb.code.tex': {
        "repository": 'paper/texmf_vendor/pgfplotsutil.verb.code.tex',
        "sha256": '878385031a1d3ea317938785f956d075fd419415bc00204b28f3f6792bb30d29',
        "bytes": 3286,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tables/growing_window_pareto.tex': {
        "repository": 'paper/tables/growing_window_pareto.tex',
        "sha256": '81f15cc641dad695d41fdeebf479c3371d963e930b19d1fbab27ee3386ce267c',
        "bytes": 363,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'tables/transport_instantiation_performance.tex': {
        "repository": 'paper/tables/transport_instantiation_performance.tex',
        "sha256": '5b2ea6000bfc123d9f52b38f37ddbb5aafb7eeb55139c8876a29d33879ee13ad',
        "bytes": 2269,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'tables/transport_instantiation_tightness.tex': {
        "repository": 'paper/tables/transport_instantiation_tightness.tex',
        "sha256": '940106f9f33decab26a9033277c5bc354c6c2e8d09dc629b5b3b6954deb45311',
        "bytes": 1761,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'tables/transport_instantiation_validity.tex': {
        "repository": 'paper/tables/transport_instantiation_validity.tex',
        "sha256": '0ec0451563890ea9373a0710bbcbc33b2db28a14e405a798e6033062fab7634a',
        "bytes": 1765,
        "role": 'generated-artifact',
        "ships_in": 'supplement',
    },
    'tikzlibrarydecorations.softclip.code.tex': {
        "repository": 'paper/texmf_vendor/tikzlibrarydecorations.softclip.code.tex',
        "sha256": 'dc56593a617f4a7512dce6c5ab16a80a5f53b164e93419937c9e249d61239739',
        "bytes": 15939,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tikzlibraryfillbetween.code.tex': {
        "repository": 'paper/texmf_vendor/tikzlibraryfillbetween.code.tex',
        "sha256": '14de4093b72cd84659cdd31b064827be0c88085428ead999080b43bcfc1e2d20',
        "bytes": 18491,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tikzlibrarypgfplots.decorations.softclip.code.tex': {
        "repository": 'paper/texmf_vendor/tikzlibrarypgfplots.decorations.softclip.code.tex',
        "sha256": '4d141d667fa77f766c592b62b6b8fddef8cf936be983b73c92340e94360c7a70',
        "bytes": 1280,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tikzlibrarypgfplots.fillbetween.code.tex': {
        "repository": 'paper/texmf_vendor/tikzlibrarypgfplots.fillbetween.code.tex',
        "sha256": '1f30469b33df72c0dc7fd2da567fd42fc08e679dfcbb0d5e3a82b710841d24ca',
        "bytes": 8022,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tikzlibrarypgfplots.groupplots.code.tex': {
        "repository": 'paper/texmf_vendor/tikzlibrarypgfplots.groupplots.code.tex',
        "sha256": '27ad8052f7708da5f355f2754ceb274cc622da405aec7b93be7224d076bdfe42',
        "bytes": 21935,
        "role": 'vendored-package',
        "ships_in": 'source',
    },
    'tmlr.sty': {
        "repository": 'paper/tmlr_style/tmlr.sty',
        "sha256": '816214ff5919aa457b6b443bee52b15d9561421417b7f8a50cc84651519f0002',
        "bytes": 6560,
        "role": 'venue-template',
        "ships_in": 'source',
    },
    'transport_experiment.tex': {
        "repository": 'paper/transport_experiment.tex',
        "sha256": '86a1d74a3b9e00b409f875e0bbee2cf431b7abd07e9103c8f006f6b37f22cdc2',
        "bytes": 8731,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'transport_experiment_appendix.tex': {
        "repository": 'paper/transport_experiment_appendix.tex',
        "sha256": 'b45873124d1ff8915a71f05ff32c704b24c92e44a23ae70ada38cb083e837939',
        "bytes": 3665,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'transport_proofs.tex': {
        "repository": 'paper/transport_proofs.tex',
        "sha256": 'd0c6fcdfd9048fb5340446f92a7a2f56cda04eedf02687c3d5bcec8039956fde',
        "bytes": 17283,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
    'transport_theory.tex': {
        "repository": 'paper/transport_theory.tex',
        "sha256": 'd18a7a49b9b9c760cf9ce351e375e853017b10360437a301121f53e84d94db8e',
        "bytes": 29579,
        "role": 'manuscript-source',
        "ships_in": 'supplement',
    },
}

#: The shipped tools whose bytes decide whether a reviewer's verification
#: passes, pinned here so that no one of them can authorize itself.
#:
#: `tools/numeric_context_pins.py` is the reason this exists.  It is generated
#: data: it records, for every declared number in the manuscript, the exact
#: enclosing sentence or block that number is allowed to appear in.  It also
#: ships with the supplement, because the shipped ledger reads it.  Inside an
#: unpacked supplement, then, someone could edit a manuscript source *and*
#: regenerate the pin for it, and the ledger -- comparing the source against a
#: record derived from that same edited source -- would agree with itself and
#: pass.
#:
#: Pinning the digest here breaks that loop.  This module is the tree's
#: authentication root: packaging refuses to build if the bytes it is about to
#: ship do not match these constants, the shipped ledger checks them before it
#: trusts a single pin, and `release_manifest.json` records them again outside
#: the archive.  A self-consistent edit now has to reach three files, one of
#: which is the file doing the checking.
#:
#: This is a binding, not a signature: an offline archive has no cryptographic
#: root, and a reviewer who wants certainty compares these bytes against the
#: release manifest, which never ships.
SHIPPED_TOOL_DIGESTS: dict[str, str] = {
    "tools/numeric_context_pins.py":
        "5c2c5217be1cc4d4595c5562dc40b4ae5f6b8cfdffacd5f5565e86fdb8adb3fd",
}

#: Every field a declaration record must carry, and nothing else may be missing.
REQUIRED_RECORD_FIELDS = frozenset({
    "path", "field", "replacement", "original_sha256", "packaged_sha256",
    "original_bytes", "packaged_bytes", "removed_value_class", "reason",
})

#: Fields a reviewer-visible record must never carry.
FORBIDDEN_RECORD_FIELDS = frozenset({"removed_value_internal_only", "source_path"})

#: The exact top-level key set the declaration must have: no fewer, no more.
REQUIRED_DECLARATION_KEYS = frozenset({
    "schema_version", "what_this_is", "how_to_tell_it_did_not_change_the_numbers",
    "replacement_token_is_not_a_revision", "sidecars", "transformed",
})

DECLARATION_SCHEMA_VERSION = 1


def sidecar_text(relative: str) -> str:
    """The exact bytes the `.sha256` next to a sanitized file must contain."""

    return f"{CONTRACT[relative]['packaged_sha256']}  {Path(relative).name}\n"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def is_packaged_tree(root: Path) -> bool:
    """True when `root` is an anonymous supplement rather than the repository."""

    return (root / DECLARATION_NAME).is_file()


def package_required(explicit: bool | None = None) -> bool:
    """Resolve the package-required signal: explicit flag first, then the env.

    This is an explicit contract, never a guess about the tree.  A checker must
    be told that it is looking at a package; it must not infer it from paths,
    because the whole point is that a tampered package may be missing exactly
    the file such an inference would key on.
    """

    if explicit is not None:
        return bool(explicit)
    return os.environ.get(ENV_REQUIRE_PACKAGE, "").strip().lower() in {
        "1", "true", "yes", "on",
    }


def missing_declaration_result(root: Path) -> tuple[str, bool, str]:
    """The failure emitted when package mode is required but nothing declares it."""

    return (
        f"{DECLARATION_NAME} is present (required package mode)",
        False,
        f"no {DECLARATION_NAME} at {root}. Package mode was required, so this "
        "tree cannot be treated as the repository: an anonymous supplement that "
        "has lost its declaration is either incomplete or has been reverted to "
        "the original, author-linked evidence, and both must fail rather than "
        "silently fall back to repository semantics.",
    )


def original_sha256(relative: str) -> str | None:
    """The pinned digest of the original evidence behind a sanitized path."""

    record = CONTRACT.get(str(relative))
    return str(record["original_sha256"]) if record else None


def check_shipped_tools(root: Path) -> list[tuple[str, bool, str]]:
    """Verify the shipped tools whose bytes decide a verification result.

    Runs in both modes: the repository copy and the packaged copy are the same
    bytes, so both are held to the same pins.  A tool that is absent from this
    tree is not a failure -- `source.zip` carries none of them -- but a tool
    that is present and does not match is.
    """

    results: list[tuple[str, bool, str]] = []
    for relative, pinned in sorted(SHIPPED_TOOL_DIGESTS.items()):
        path = root / relative
        if not path.is_file():
            continue
        actual = sha256_file(path)
        results.append((
            f"shipped tool matches the pinned contract: {relative}",
            actual == pinned,
            f"sha256 {actual} vs pinned {pinned}. This file is generated data "
            "that the ledger reads; editing a source and its pin together must "
            "not authorize itself, so the pin is held here as well.",
        ))
    return results


def check_provenance(root: Path) -> list[tuple[str, bool, str]]:
    """Verify the shipped provenance records against their pinned constants.

    Runs in both modes: these bytes are the same in the repository and in a
    package, because the anonymizing transform does not touch them.
    """

    results: list[tuple[str, bool, str]] = []
    for relative, pinned in sorted(PROVENANCE_PINS.items()):
        path = root / relative
        if not path.is_file():
            results.append((f"provenance record present: {relative}", False,
                            "missing"))
            continue
        actual = sha256_file(path)
        size = path.stat().st_size
        results.append((
            f"provenance bytes match the pinned contract: {relative}",
            actual == pinned["sha256"] and size == pinned["bytes"],
            f"sha256 {actual} vs pinned {pinned['sha256']}; "
            f"{size} bytes vs pinned {pinned['bytes']}",
        ))
        try:
            record = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as error:
            results.append((f"provenance parses: {relative}", False,
                            repr(error)))
            continue
        problems = []
        if record.get("artifact") != pinned["describes"]:
            problems.append(f"artifact={record.get('artifact')!r}")
        if record.get("artifact_sha256") != pinned["artifact_sha256"]:
            problems.append(
                f"artifact_sha256={record.get('artifact_sha256')!r}")
        if record.get("input_set_sha256") != pinned["input_set_sha256"]:
            problems.append(
                f"input_set_sha256={record.get('input_set_sha256')!r}")
        if record.get("schema_version") != pinned["schema_version"]:
            problems.append(f"schema_version={record.get('schema_version')!r}")
        inputs = record.get("inputs")
        if not isinstance(inputs, list) or len(inputs) != pinned["input_count"]:
            problems.append(
                f"inputs={len(inputs) if isinstance(inputs, list) else inputs} "
                f"vs pinned {pinned['input_count']}")
        elif not all(isinstance(item, dict) and item.get("path")
                     and isinstance(item.get("sha256"), str)
                     and len(item["sha256"]) == 64 for item in inputs):
            problems.append("an input entry has no path or no 64-hex digest")
        results.append((
            f"provenance still binds its artifact: {relative}",
            not problems,
            "; ".join(problems),
        ))
    return results


def check(root: Path, *, require_package: bool | None = None
          ) -> list[tuple[str, bool, str]]:
    """Validate a packaged tree against the pinned contract.

    Returns `(name, ok, detail)` triples.  The caller decides how to report
    them; every `ok=False` is a hard failure.

    With package mode required, a tree without a declaration yields a single
    failing result rather than an empty pass.
    """

    results: list[tuple[str, bool, str]] = []

    def record_result(name: str, ok: bool, detail: str = "") -> None:
        results.append((name, ok, detail))

    # The provenance pins hold in both modes: the transform does not touch
    # those bytes, so a repository check and a package check expect the same
    # ones.  They run before the declaration so that a tree with no declaration
    # is still held to them.
    results.extend(check_provenance(root))
    results.extend(check_shipped_tools(root))

    if not is_packaged_tree(root):
        if package_required(require_package):
            results.append(missing_declaration_result(root))
        return results

    declaration_path = root / DECLARATION_NAME
    try:
        declaration = json.loads(declaration_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        record_result(f"{DECLARATION_NAME} parses", False, repr(error))
        return results

    # ---- the declaration must have the shape we pinned --------------------
    # Exact equality, not containment.  A declaration carrying extra top-level
    # keys is not the document this contract describes: the extra key may say
    # something a reviewer will read and act on, and nothing here has checked
    # it.  Missing and unexpected keys are both reported so the failure names
    # what is actually wrong.
    declared_keys = set(declaration)
    missing_keys = REQUIRED_DECLARATION_KEYS - declared_keys
    unexpected_keys = declared_keys - REQUIRED_DECLARATION_KEYS
    record_result(
        f"{DECLARATION_NAME} has exactly the pinned top-level schema",
        not missing_keys and not unexpected_keys
        and declaration.get("schema_version") == DECLARATION_SCHEMA_VERSION,
        f"missing {sorted(missing_keys)}; unexpected {sorted(unexpected_keys)}; "
        f"schema_version={declaration.get('schema_version')!r}",
    )

    transformed = declaration.get("transformed")
    if not isinstance(transformed, list):
        record_result(f"{DECLARATION_NAME} lists transformed records", False,
                      f"got {type(transformed).__name__}")
        return results

    declared_paths = [record.get("path") for record in transformed]
    record_result(
        "declared record set is exactly the pinned set",
        sorted(p for p in declared_paths if isinstance(p, str)) == sorted(CONTRACT)
        and len(declared_paths) == len(CONTRACT),
        f"declared {sorted(str(p) for p in declared_paths)}; "
        f"pinned {sorted(CONTRACT)}",
    )

    by_path = {
        record.get("path"): record
        for record in transformed
        if isinstance(record, dict)
    }

    # ---- each pinned path, checked against code and not against the file --
    for relative, pinned in sorted(CONTRACT.items()):
        path = root / relative
        if not path.is_file():
            record_result(f"sanitized file present: {relative}", False, "missing")
            continue

        actual_bytes = path.stat().st_size
        actual_sha = sha256_file(path)
        record_result(
            f"sanitized bytes match the pinned contract: {relative}",
            actual_sha == pinned["packaged_sha256"]
            and actual_bytes == pinned["packaged_bytes"],
            f"sha256 {actual_sha} vs pinned {pinned['packaged_sha256']}; "
            f"{actual_bytes} bytes vs pinned {pinned['packaged_bytes']}",
        )

        # the redacted field must hold exactly the pinned placeholder
        try:
            loaded = json.loads(path.read_text(encoding="utf-8"))
            field_value = loaded.get(PACKAGED_FIELD)
        except (OSError, ValueError) as error:
            field_value = f"<unreadable: {error!r}>"
        record_result(
            f"redacted field holds the pinned token: {relative}",
            field_value == REPLACEMENT_TOKEN,
            f"{PACKAGED_FIELD}={field_value!r}, pinned {REPLACEMENT_TOKEN!r}",
        )

        # the sidecar must be exactly the pinned text, not merely self-consistent
        sidecar = Path(f"{path}.sha256")
        try:
            sidecar_actual = sidecar.read_text(encoding="ascii")
        except OSError:
            sidecar_actual = ""
        record_result(
            f"sidecar text matches the pinned contract: {relative}.sha256",
            sidecar_actual == sidecar_text(relative),
            f"sidecar {sidecar_actual!r}, pinned {sidecar_text(relative)!r}",
        )

        # and the declaration must agree with the pinned values, not define them
        declared = by_path.get(relative)
        if declared is None:
            record_result(f"declaration covers {relative}", False, "no record")
            continue
        field_problems = []
        if set(declared) - REQUIRED_RECORD_FIELDS:
            field_problems.append(
                f"unexpected fields {sorted(set(declared) - REQUIRED_RECORD_FIELDS)}")
        if REQUIRED_RECORD_FIELDS - set(declared):
            field_problems.append(
                f"missing fields {sorted(REQUIRED_RECORD_FIELDS - set(declared))}")
        if set(declared) & FORBIDDEN_RECORD_FIELDS:
            field_problems.append(
                f"internal-only fields leaked "
                f"{sorted(set(declared) & FORBIDDEN_RECORD_FIELDS)}")
        for key in ("original_sha256", "packaged_sha256",
                    "original_bytes", "packaged_bytes"):
            if declared.get(key) != pinned[key]:
                field_problems.append(
                    f"{key}={declared.get(key)!r} but pinned {pinned[key]!r}")
        if declared.get("field") != PACKAGED_FIELD:
            field_problems.append(f"field={declared.get('field')!r}")
        if declared.get("replacement") != REPLACEMENT_TOKEN:
            field_problems.append(f"replacement={declared.get('replacement')!r}")
        record_result(
            f"declaration agrees with the pinned contract: {relative}",
            not field_problems,
            "; ".join(field_problems),
        )

    return results


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument(
        "--require-package", action="store_true", default=None,
        help="fail if the tree is not an anonymous package. The shipped "
             "supplement entry point always passes this; it is also implied by "
             f"{ENV_REQUIRE_PACKAGE}=1.")
    parser.add_argument(
        "--list-pinned", action="store_true",
        help="print the paths this contract verifies from pinned constants, "
             "one per line, and exit. The supplement's sidecar sweep uses it "
             "so that a file covered here is not reported as uncovered there.")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    required = package_required(args.require_package)

    if args.list_pinned:
        for relative in sorted(set(CONTRACT) | set(PROVENANCE_PINS)):
            print(relative)
            print(f"{relative}.sha256")
        return 0

    if not is_packaged_tree(root) and not required:
        # Repository mode has nothing to say about the declaration, but the
        # provenance pins hold here too and used to go unchecked entirely.
        print(f"no {DECLARATION_NAME} at {root}: this is not an anonymous "
              "package, so there is no anonymization contract to check "
              "(optional repository mode)")
        # The provenance pins and the shipped-tool pins both hold here: neither
        # depends on the anonymizing transform, and the repository copy of a
        # shipped tool is the same bytes the supplement carries.
        results = check_provenance(root) + check_shipped_tools(root)
        bad = sum(1 for _, ok, _ in results if not ok)
        for name, ok, detail in results:
            print(f"{'PASS' if ok else 'FAIL'}  {name}")
            if not ok:
                print(f"        -> {detail}")
        print()
        print(f"{len(results) - bad} of {len(results)} pinned provenance and "
              "shipped-tool checks passed")
        return 1 if bad else 0

    print(f"mode: {'REQUIRED anonymous package' if required else 'optional'}")
    results = check(root, require_package=required)
    bad = 0
    for name, ok, detail in results:
        print(f"{'PASS' if ok else 'FAIL'}  {name}")
        if not ok:
            print(f"        -> {detail}")
            bad += 1
    print()
    print(f"{len(results) - bad} of {len(results)} anonymous-package contract "
          "checks passed, against constants pinned in shipped code")
    if bad:
        print("the packaged tree does not match the contract; do not trust it")
    return 1 if bad else 0


if __name__ == "__main__":
    raise SystemExit(main())
