python_binary(
    name = "pytest_runner",
    main = "pytest_main.py",
    deps = [
        "//experiments:lib",
        "//paper:paper_data",
        "fbsource//third-party/pypi/pytest/7.2.2:py",
    ],
    visibility = ["PUBLIC"],
)
