python_binary(
    name = "pytest_runner",
    main = "pytest_main.py",
    deps = [
        "//experiments:lib",
        "//paper:paper_data",
        "fbsource//third-party/pypi/pytest/7.2.2:py",
    ],
    visibility = ["PUBLIC"],
)

python_binary(
    name = "prepare_covtype_benchmark",
    main = "prepare_covtype_benchmark.py",
    deps = [
        "//experiments/realistic_transport:lib",
        "fbsource//third-party/pypi/scikit-learn/1.5.1:py",
    ],
)
